### ISSUE TITLE
Not working with categories or entry types?

### ISSUE THREAD

**Issue by bossanova808** [mmikkel/CpSortableCustomColumns-Craft#1]
If I am reading the docs right, this should work for sort by entry types?  I am not seeing this work.

It appears to work, I get a spinner etc, but the resulting list is not sorted.

![2016-02-08_15-27-35](https://cloud.githubusercontent.com/assets/731309/12878416/a43b9b4c-ce78-11e5-9c0b-6c88bfd19096.png)

I am not sure if categories are supported at all, but the docs do mention entry types.

Any tips?

**Comment by mmikkel** [comment]
Hi @bossanova808, thanks for reporting! The issue with Entry Types should be fixed in v. 1.0.2, which I just pushed.

Unfortunately, Craft doesn't actually support sorting the index tables on relational fields (Categories, Entries, Tags etc), so I'll have to close the Categories issue as a wontfix for now, sorry.

**Comment by bossanova808** [comment]
No probs re: categories and many thanks for the fix, will try it out tomorrow!
